### ISSUE TITLE
Add max-width to images and fix spaces

### ISSUE THREAD

**Issue by LailaAli** [fostyler/fos-flagship#13]
## Issue Description (Text, Scribble, Wireframe, Design)

Add max-width to images on landing.
Decrease space between
- Get in touch button and form to 80px
- Form and Website coming soon text to 80px

## Visuals (Text, Scribble, Wireframe, Design)

![Image](https://user-images.githubusercontent.com/31609683/249628191-0008989f-db05-4c4d-821b-cf458b41d35a.png)

![Image](https://user-images.githubusercontent.com/31609683/249628347-767dd3cc-9c87-430a-8411-e4766569cdc7.png)

![Image](https://user-images.githubusercontent.com/31609683/249629266-860eda5e-3c75-4ae9-9bdd-cd062253b3ba.png)

![Image](https://user-images.githubusercontent.com/31609683/249629606-8b135997-25ac-4c2b-a4c8-fc6ec8eff83f.png)

## Acceptance Criteria
- (functional descriptions)

## Tasks
- [ ] We need to add a max width to the bubble graphic in the top left corner.
- [ ] Wrap all the main content and rocket in a div with a max-width of 1080px. Rocket should stay close to the word "needs".

## Size
- [ ] mobile
- [ ] tablet
- [ ] desktop

## Blocked By

#000

## Blocking

#000

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
